config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :lists do
    resources :list_items
    resources :list_categories, only: %i[index show]
  end
  resources :categories, only: %i[index show]
  resources :users, only: %i[show]
  get "mylists", to: "lists#mylists", as: :"lists/mylists"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "lists#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :list_categories, dependent: :destroy
  has_many :lists, through: :list_categories

  validates :name, presence: true, uniqueness: true
end

app/models/list.rb
class List < ApplicationRecord
  belongs_to :user
  has_many :list_categories, dependent: :destroy
  has_many :categories, through: :list_categories
  has_many :list_items, dependent: :destroy
end

app/models/list_category.rb
class ListCategory < ApplicationRecord
  belongs_to :list
  belongs_to :category

  validates :category_id, uniqueness: { scope: :list_id }
end

app/models/list_item.rb
class ListItem < ApplicationRecord
  belongs_to :list
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_many :lists, dependent: :destroy

  validates :email, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :first_name, :last_name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name ])
  end

  def authenticate_user!(opts = {})
    unless user_signed_in?
      flash[:alert] = "You need to sign in or sign up before continuing."
      redirect_to new_user_session_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @lists = @category.lists
    @page_title = "#{@category.name}"
    render "lists/index"
  end
end

app/controllers/list_categories_controller.rb
class ListCategoriesController < ApplicationController
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  def index
    @list_items = ListItem.all
  end

  def show
    @list_item = ListItem.find(params[:id])
  end

  def new
    @list_item = ListItem.new
  end

  def create
    ListItem.create!(list_item_params.merge(list: list))
  end

  def edit
    @list_item = ListItem.find(params[:id])
  end

  def update
    @list_item.update!(list_item_params)
  end

  def destroy
    @list_item = ListItem.find(params[:id])
    @list_item.destroy!
  end

  def list_item_params
    params.require(:list_item).permit(:name, :position)
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!, except: %i[index show]
  before_action :set_list, only: %i[show edit update destroy]
  before_action :authorize_user!, only: %i[edit update destroy]

  def index
    @page_title = "All Lists"
    @lists = List.all
  end

  def show
  end

  def new
    @list = current_user.lists.new
    (params[:items_count] || 3).to_i.times do |i|
      @list.list_items.build(position: i + 1)
    end

    @categories = Category.all.pluck(:name, :id)
  end

  def edit
  end

  def mylists
    @lists = current_user.lists
    @is_mylists = true
    @page_title = "My Lists"
    render :index
  end

  def create
    @list = current_user.lists.new(list_params)

    if @list.save
      redirect_to @list, notice: "List was successfully created."
    else
      render :new, status: :unprocessable_entity
    end
  end

  def update
    if @list.update(list_params)
      redirect_to @list, notice: "List was successfully updated."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @list.destroy
    redirect_to lists_url, notice: "List was successfully deleted."
  end

  private

  def set_list
    @list = List.find(params[:id])
  end

  def authorize_user!
    return if @list.user == current_user
      redirect_to lists_path, alert: "You are not authorized to perform this action."
  end

  def list_params
    params.require(:list).permit(
      :name,
      :description,
      category_ids: [],
      list_categories_attributes: [ :id, :category_id, :_destroy ],
      list_items_attributes: [ :id, :name, :position, :_destroy ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def category_colors(category_name)
    colors = {
      "Travel" => "#75b9be",
      "Sports & Hiking" => "#AF7A6D",
      "Music" => "#cc76a1",
      "Art" => "#F5A623",
      "Technology" => "#797b84",
      "Books" => "#de7c5a",
      "Food & Drink" => "#9ae19d",
      "Health & Fitness" => "#b7990d",
      "Movies" => "#4a90e2",
      "Fashion & Beauty" => "#d14d72",
      "Faith & Spirituality" => "#ffbfb7",
      "Science" => "#bbc5aa"
    }
    colors[category_name] || { background: "#9B9B9B" }
  end

  def category_icon(category)
    icons = {
      "Travel" => "fa-solid fa-plane",
      "Sports & Hiking" => "fa-solid fa-person-hiking",
      "Music" => "fa-solid fa-music",
      "Art" => "fa-solid fa-palette",
      "Technology" => "fa-solid fa-microchip",
      "Books" => "fa-solid fa-book",
      "Food & Drink" => "fa-solid fa-utensils",
      "Health & Fitness" => "fa-solid fa-heart-pulse",
      "Movies" => "fa-solid fa-film",
      "Fashion & Beauty" => "fa-solid fa-shirt",
      "Faith & Spirituality" => "fa-solid fa-spa",
      "Science" => "fa-solid fa-flask"
    }
    icons[category.name] || "fa-solid fa-tag"
  end
end

app/views/categories/index.html.erb
<div class="categories-container">
  <% @categories.each do |category| %>
    <%= link_to category_path(category), class: "category-card-link" do %>
    <div class="category-card" style="background-color: <%= category_colors(category.name) %>;">
      <div class="category-icon">
        <i class="<%= category_icon(category) %> category-icon"></i>
      </div>
      <div class="category-name"><%= category.name %></div>
    </div>
    <% end %>
  <% end %>
</div>

app/views/categories/show.html.erb
<h1><%= @category.name %></h1>

<div>
  <% @category.lists.each do |list| %>
    <div class="list-item">
      <h2><%= link_to list.name, list_path(list) %></h2>
    </div>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<!--<footer>-->
<!--  <div class="container">-->
<!--    <p>&copy; <%#= Time.current.year %> MyWebsite. All rights reserved.</p>-->
<!--  </div>-->
<!--</footer>-->

app/views/layouts/_navbar.html.erb
<div class="navbar-container">
  <div class="nav-tabs">
    <div class="nav-tab-item <%= 'active' if current_page?(root_path) %> ">
      <%= link_to "Home", root_path %>
    </div>
    <div class="nav-tab-item <%= 'active' if current_page?(categories_path) %> ">
      <%= link_to "Discover", categories_path %>
    </div>
  </div>

    <% if current_user %>
    <div class="nav-tabs">
      <div class="nav-tab-item my-lists <%= 'active' if current_page?(lists_mylists_path) %> ">
        <%= link_to "My lists", lists_mylists_path %></div>
      <div class="nav-tab-item user-info">
        <div class="user-info-dropdown">
          <button class="dropdown-toggle" style="font-weight: bold;">
            Welcome, <%= current_user.first_name %>
          </button>
          <div class="dropdown-menu">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= button_to "Sign out", destroy_user_session_path, method: :delete, class: "dropdown-item signout-link" %>
          </div>
        </div>
      </div>
    </div>
    <% else %>
      <div class="nav-tab-item session-tabs">
          <%= link_to "Sign in", new_user_session_path %>
          <%= link_to "Sign up", new_user_registration_path %>
      </div>
    <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Rails App Ctd" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
      integrity="sha512-Kc323vGBEqzTmouAECnVceyQqyqdsSiqLQISBL29aUW4U/M7pSPA/gEUZQqv1cwx4OnYxTxve5UMg5GT6L4JJg=="
      crossorigin="anonymous"
      referrerpolicy="no-referrer"
      />

    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render partial: "layouts/navbar" %>

    <% flash.each do |key, value| %>
    <div class="flash-message alert alert-<%= key == 'alert' ? 'danger' : 'success' %>">
      <%= value %>
    </div>
  <% end %>

    <%= yield %>
    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/lists/_form.html.erb
<div class="form-container">
  <%= form_with(model: @list) do |form|%>
  <% if @list.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(@list.errors.count, "error") %> prohibited this list from being saved:</h2>

      <ul>
        <% @list.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="list-name-container">
    <%= form.text_field :name, placeholder: "List Name", class: "list-input" %>
  </div>

  <div class="list-description-container">
    <%= form.textarea :description, placeholder: "Description limited to 150 characters", class: "description_input" %>
  </div>

  <div class="categories-message">
    <%= form.label :categories, "Categories (choose up to 2)", style: "display: block" %>
  </div>
  <div class="list-categories">
    <%= form.collection_check_boxes :category_ids, Category.all, :id, :name do |b| %>
    <div class="list-category-tag">
      <%= b.label style: "background-color: #{category_colors(b.text)}", class: "list-category-item" do %>
      <%= b.check_box class: "category-checkbox" %> <%= b.text %>
      <% end %>
    </div>
    <% end %>
  </div>

<!--  <h3>List Items</h3>-->
  <div id="list-items" class="list-items">
    <%= form.fields_for :list_items do |item_form| %>
      <div class="list-item-fields">
        <span class="item-position"><%= item_form.index.to_i + 1 %></span>
        <%= item_form.text_field :name, placeholder: "List Item", class: "list-item-input" %>
        <%= item_form.hidden_field :position, value: item_form.index.to_i + 1 %>
        <%= item_form.hidden_field :_destroy %>
        <button type="button" class="remove-item">
          <i class="fa-solid fa-trash-can"></i>
        </button>
      </div>
    <% end %>
  </div>

  <div class="add-item">
    <button class="add-item-button" type="button" id="add-item">+ Add Item</button>
  </div>

  <div class="submit-button-container">
    <%= form.submit class: "submit-button" %>
    <% if @list.persisted? %>
      <%= button_to "Delete this list", @list, method: :delete, data: { confirm: "Are you sure?" }, class: "submit-button" %>
    <% end %>
  </div>
<% end %>

</div>

app/views/lists/_list_item_fields.html.erb
<div class="list-item-fields">
  <p><strong>Position:</strong> <span class="item-position"><%= form.object.position %></span></p>

  <%= form.label :name, "Item Name", style: "display: block" %>
  <%= form.text_field :name %>
</div>

app/views/lists/edit.html.erb
<% content_for :name, "Edit List" %>

<!--<h1>Edit List</h1>-->

<%= render "form", list: @list %>
<%#= button_to "Delete this list", @list, method: :delete, data: { confirm: "Are you sure?" }, class: "submit-button" %>
<br>

<div class="nav-buttons", style="display: flex; flex-direction: row;">
  <div class="back-button">
    <%= link_to "Show this list", @list %>
  </div>
  <i class="fa-solid fa-ellipsis-vertical"></i>
  <div class="back-button">
    <%= link_to "Back to All lists", lists_path %>
  </div>
</div>

app/views/lists/index.html.erb
<!--<h1>-->
  <%#= @page_title %>
<!--</h1>-->

<% if @lists.any? %>
  <div class="lists-container">
    <% @lists.each do |list| %>
      <div class="list-card">
        <div class="list-name">
          <%= link_to list.name, list_path(list), class: "list-name" %>
        </div>
        <div class="user-tag">
          By:
          <% if list.user == current_user %>
            <%= link_to "You", user_path(current_user) %>
          <% else %>
          <%= link_to "#{list.user.first_name} #{list.user.last_name}", user_path(list.user) if list.user %>
          <% end %>
        </div>

        <div class="list-actions">
          <% if list.user == current_user %>
            <%= link_to edit_list_path(list) do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
          <% end %>
        </div>
        <div class="categories">
          <% list.categories.each do |category| %>
            <div>
              <%= link_to category.name, category_path(category), style: "background-color: #{category_colors(category.name)}", class: "category-tag" %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <p>No lists found</p>
<% end %>

<div class="new-list"><%= link_to "New List", new_list_path, class: "add-btn" %></div>

app/views/lists/mylists.html.erb
<h1>My Lists</h1>

<div>
  <% @lists.each do |list| %>
    <div class="list-item">
      <h3><%= link_to list.name, list_path(list) %></h3>
    </div>
    <div><%= link_to "Edit List", edit_list_path(list) %></div>
  <% end %>
</div>

app/views/lists/new.html.erb
<% content_for :title, "New List" %>

<!--<h1>New List</h1>-->
<%= render "form", list: @list %>

<div class="back-button">
  <%= link_to "Back to All Lists", lists_path %>
</div>

app/views/lists/show.html.erb
<div class="list-show-container">
  <div class="list-show-name-container">
    <div class="list-name">
      <%= @list.name %>
    </div>

  <div class="user-tag">
    Created by:
    <%= link_to "#{@list.user.first_name} #{@list.user.last_name}", user_path(@list.user) if @list.user %>
  </div>
</div>

  <div class="list-show-description">
    <%= @list.description %>
  </div>

  <div class="categories">
    <% @list.categories.each do |category| %>
      <div>
          <%=link_to category.name, category_path(category), style: "background-color: #{category_colors(category.name)}", class: "category-tag" %>
      </div>
    <% end %>
  </div>

  <ol class="items-list">
      <% @list.list_items.each do |item| %>
        <li class="item">
          <%= item.name %>
        </li>
      <% end %>
  </ol>


  <div class="list-show-actions">
    <% if @list.user == current_user %>
      <%= link_to  edit_list_path(@list) do %>
        <i class="fa-solid fa-pen-to-square edit-icon"></i>
      <% end %>
      <%= button_to @list, method: :delete, data: { turbo_confirm: "Are you sure?" } do %>
        <i class="fa-solid fa-trash-can delete-icon"></i>
      <% end %>
    <% end %>
  </div>

  <div>
    <%= link_to "Back to All Lists", lists_path, class: "back-button" %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-profile-container">
  <p class="user-name"><%= "#{@user.first_name} #{@user.last_name}" %></p>
  <p class="user-email">Email: <%= @user.email %></p>

  <div class="user-actions">
    <% if current_user == @user %>
      <%= link_to 'Edit Profile', edit_user_registration_path, class: "user-action-button" %>
      <%= button_to "Sign out", destroy_user_session_path, method: 'delete', class: "user-action-button" %>
    <% end %>
  </div>
</div>
<div class="user-lists-header">
  <%= current_user == @user ? "My Lists" : "Lists by this user" %>
</div>

<% if @user.lists.any? %>
  <div class="lists-container">
    <% @user.lists.each do |list| %>
      <div class="list-card">
        <div class="list-info">
          <%= link_to list.name, list, class: "list-name" %>
          <div class="categories">
          <% list.categories.each do |category| %>
            <div>
              <%= link_to category.name, category_path(category), style: "background-color: #{category_colors(category.name)}", class: "category-tag" %>
            </div>
          <% end %>
        </div>
        </div>
        <% if current_user == @user %>
          <div class="list-actions" style="display: flex; flex-direction: column">
            <%= link_to edit_list_path(list) do %>
              <i class="fa-solid fa-pen-to-square"></i>
            <% end %>
            <%= link_to list, method: :delete, data: { confirm: 'Are you sure?' } do %>
              <i class="fa-solid fa-trash-can"></i>
            <% end %>
          </div>
        <% end %>
        <div class="created-at-list">
          Created at: <%= list.created_at.strftime("%B %d, %Y") %>
        </div>
      </div>
    <% end %>
  </div>
<% else %>
  <% if current_user == @user %>
    <p style="margin-left: 2rem">
      You have no lists yet. <%= link_to 'Create your first list', new_list_path, class: "create-list-link" %>
    </p>
  <% else %>
    <p style="margin-left: 2rem">
      This user has no lists yet.
    </p>
  <% end %>
<% end %>